# Generated by Django 4.2.7 on 2023-11-27 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myLibrary_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn_number', models.CharField(max_length=200)),
                ('book_name', models.CharField(max_length=200)),
                ('book_author', models.CharField(max_length=200)),
                ('book_price', models.IntegerField()),
                ('book_quntity', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='reader',
            name='reader_contact',
            field=models.IntegerField(),
        ),
    ]
