# Generated by Django 4.2.7 on 2023-11-27 13:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myLibrary_app', '0002_book_alter_reader_reader_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reader',
            name='id',
        ),
        migrations.AlterField(
            model_name='reader',
            name='reader_contact',
            field=models.IntegerField(validators=[django.core.validators.MaxLengthValidator(9999999999)]),
        ),
        migrations.AlterField(
            model_name='reader',
            name='reference_id',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
