# Generated by Django 4.2.7 on 2023-11-27 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myLibrary_app', '0005_readerss_delete_reader'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readerss',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
